version: '3'

services:
  app:
    build: .
    container_name: quotationproject
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - .:/app
    command: ["java", "-jar", "/app/target/QuotationProject-0.0.1-SNAPSHOT.jar"]
